apiVersion: v1    # version de l'appli
kind: Pod 
metadata:        
  name: simple-webapp-color 
  labels:
    app: web 
spec:
  containers:
  - name: web 
    image: mmumshad/simple-webapp-color 
    ports:
      - containerPort: 8080     # port exposion dans le cluster 
    env:
      - name: APP_COLOR
        value: red 
